# Generated by Django 5.2.7 on 2025-10-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="railway.trip",
            ),
        ),
    ]
