# Generated by Django 5.2.7 on 2025-10-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0003_alter_ticket_trip"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("seat", "trip"), name="unique_ticket_seat_trip"
            ),
        ),
    ]
