# Generated by Django 5.2.7 on 2025-10-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0004_ticket_unique_ticket_seat_trip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("cargo", "seat")},
        ),
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket_seat_trip",
        ),
    ]
