# Generated by Django 5.2.7 on 2025-11-05 09:05

import railway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0005_alter_ticket_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=railway.models.train_image_file_path
            ),
        ),
    ]
