# Generated by Django 5.2.7 on 2025-11-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0006_train_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="position",
            field=models.CharField(default="Driver", max_length=64),
            preserve_default=False,
        ),
    ]
